version: '3.8'

name: st-crm-api

x-common-settings: &common-settings
  platform: linux/amd64
  restart: always
  extra_hosts:
    - 'host.docker.internal:host-gateway'
  networks:
    - st-crm-api
  volumes:
    - node_modules:/app/node_modules

services:
  api:
    <<: *common-settings
    build:
      context: .
      target: production-api
      dockerfile: .docker/node/Dockerfile
    ports:
      - '${DOCKER_API_HOST:-127.0.0.1}:${DOCKER_API_PORT:-5000}:5000'

  user:
    <<: *common-settings
    build:
      context: .
      target: production-user
      dockerfile: .docker/node/Dockerfile

networks:
  st-crm-api:
    driver: bridge

volumes:
  node_modules:
